import ListQueue
import QueueStack

# testQueue = ListQueue.ListQueue()
# testQueue.enqueue(4)
# testQueue.enqueue(3)
# testQueue.enqueue(2)
# testQueue.enqueue(1)
# testQueue.enqueue(7)
# print(testQueue.poll())
# testQueue.dequeue()
# testQueue.dequeue()
# testQueue.enqueue(6)
# testQueue.enqueue(5)
# testQueue.enqueue(9)
# print(testQueue.poll())

# print(testQueue._queue)

testStack = QueueStack.QueueStack()
testStack.push(1)
testStack.push(2)
testStack.push(3)
testStack.push(4)
testStack.pop()
testStack.push(5)
testStack.push(6)
testStack.push(7)
testStack.push(8)
testStack.pop()
testStack.push(9)
testStack.push(10)
testStack.push(11)
testStack.push(12)
testStack.pop()
testStack.push(13)
testStack.push(14)
testStack.push(15)
testStack.push(16)
testStack.pop()
print(testStack._data._queue)